server:
  port: 8015
    
# DATABASE
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:~/db_dev
    driver-class-name: org.h2.Driver
    username: sa
    password:
    initialize: true
    platform: h2


# JPA 설정
spring.jpa:
  properties:
    hibernate:
      dialect: org.hibernate.dialect.H2Dialect
      format_sql: true
      show_sql: true
  hibernate:
    ddl-auto: update
  show-sql: true